services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\FeatureFlags\:
        resource: ../src/*
        exclude: ../src/{Exception,AssetsBundle.php}

    Torr\FeatureFlags\Features\FeatureFlags:
        $isDebug: '%kernel.debug%'

    Torr\FeatureFlags\Features\Loader\FeaturesFileLoader:
        $projectDir: '%kernel.project_dir%'
